@if(session('success'))
<script>
    alert("{{session('success')}}");
</script>
@endif
@if(session('message'))
<script>
    alert("{{session('message')}}");
</script>
@endif
@if(session('error'))
<script>
    alert("{{session('error')}}");
</script>
@endif